{{- if and .Values.coreApi.enabled .Values.coreApi.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.coreApi.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mosaic-life.labels" . | nindent 4 }}
    {{- include "mosaic-life.coreApi.selectorLabels" . | nindent 4 }}
  annotations:
    # Create ServiceAccount before migration job runs
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "0"
    {{- with .Values.coreApi.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
